apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/name: secretrequests.jdost.us
    app.kubernetes.io/part-of: rahsia
  name: secretrequests.jdost.us
spec:
  group: jdost.us
  names:
    kind: SecretRequest
    plural: secretrequests
    shortNames:
    - secretreq
    - sr
    singular: secretrequest
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: Request for secret to be set by administrator/operator
        type: object
        properties:
          spec:
            type: object
            properties:
              annotations:
                description: Annotations to be applied to the generated secret resource
                type: object
                additionalProperties:
                  type: string
              secrets:
                description: Keys for individual values to be defined by the user and
                  notes about that value
                type: array
                items:
                  type: object
                  properties:
                    name:
                      description: key for the requested secret value being set
                      type: string
                      pattern: '^[a-zA-Z0-9_-]+$'  # the name should only have legal characters
                    note:
                      description: notes/tooltip for the secret being requested
                      type: string
                  required:
                  - name
            required:
            - secrets
